// <auto-generated />
namespace DJProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class brodcast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brodcast));
        
        string IMigrationMetadata.Id
        {
            get { return "201302150046015_brodcast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
